# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz
      tar -xvzf ./codeql-bundle-linux64.tar.gz
      chmod +x codeql/codeql

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      codeql database create /codeql-dbs/DevOpsPOC --language=java \
          --source-root https://github.com/pritishswain/DevOpsPOC.git



- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ./codeql analyze \
      --repository pritishswain/DevOpsPOC \
      --github-url https://github.com \
      --github-auth $GITHUB_PAT \
      --commit $(Build.SourceVersion) \
      --ref $(Build.SourceBranch) \

- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release_1'
    publishLocation: 'Container'
